<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
// $this->headTitle($autor);
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->headScript()->appendFile($this->assetUrl('js/simple-lightbox.min.js'));
$this->headLink()->appendStylesheet($this->assetUrl('css/simple-lightbox.min.css'));


$lightMedia = [];
$otherMedia = [];
$whitelist = ['image/bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/svg+xml', 'video/mp4'];
foreach ($item->media() as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if (in_array($mediaType, $whitelist) || (strpos($mediaRenderer, 'youtube') !== false)) {
        $lightMedia[] = $media;
    } else {
        $otherMedia[] = $media;
    }
}
?>
<style type="text/css" media="screen">
    :root {
        --primary:
            <?php echo $primaryColor; ?>
        ;
        --secondary:
            <?php echo $secondaryColor; ?>
        ;
        --backgroundImage:
            <?php echo $backgroundImage; ?>
        ;
        --backgroundColor:
            <?php echo $backgroundColor; ?>
        ;
    }
</style>

<div class="content-sheet">
    <div class="tab-column-1">
        <?php if (count($lightMedia) > 0): ?>
            <ol id="itemfiles" class="media-list">
                <?php foreach ($lightMedia as $media): ?>
                    <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
                    <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('medium')); ?>"
                        data-download-url="<?php echo $source; ?>" class="media resource"
                        data-tweet-text="<?php echo $site->title(); ?>: «<?php echo $media->displayTitle(); ?>» por"
                        title="<?php echo $media->displayTitle(); ?>" alt="<?php echo $media->displayTitle(); ?>">
                        <?php echo $media->render(); ?>
                        <div class="title-image">
                            <?php echo $media->displayTitle(); ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        <?php endif; ?>


        <?php if (count($otherMedia) > 0): ?>
            <div id="other-media" class="property">
                <div class="values">
                    <?php foreach ($otherMedia as $media): ?>
                        <div class="value">
                            <a href="<?php echo $media->originalUrl(); ?>" title="<?php echo $media->displayTitle(); ?>"
                                alt="<?php echo $media->displayTitle(); ?>">
                                <?php echo $this->thumbnail($media, 'large'); ?>
                            </a>
                            <div class="titulo-media"><a href="<?php echo $media->originalUrl(); ?>">
                                    <?php echo $media->displayTitle(); ?>
                                    <?php echo " (formato " . strtoupper($media->extension()) . ")"; ?>
                                </a></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

    </div>

    <div class="tab-column-2">
        <p class="title-catalog-sheet">
            <?php echo ucfirst($item->resourceTemplate()->label()); ?>
        </p>
        <!--  Creates item title for the page -->
        <div class="title-file">
            <?php echo $this->pageTitle($item->displayTitle()); ?>
        </div>
         <!-- Writes item creator's name underneath item title-->
        <?php
        $autoria = $item->value('dcterms:creator', ['all' => true]);
        foreach ($autoria as $value) {
            echo '<h2 class="author-file">' . $value->asHtml() . '</h2>';
        }
        ?>
        <div class="property">
            <?php echo $item->displayValues(); ?>
        </div>
        <script>
            // selects all property titles and sets them as h4 titles
            document.querySelectorAll('.property dt').forEach(dt => {
                // Create a new h4 element
                let h4 = document.createElement('h4');

                // Copy the contents of the dt into the h4
                h4.innerHTML = dt.innerHTML;

                // Replace the dt with the h4 in the DOM
                dt.parentNode.replaceChild(h4, dt);
            });

            // function to create links -- should be moved to helpers
            let create_links = (node, tags, tag_links) => {
                let span = node.firstElementChild
                span.textContent = '';
                
                tag_links.forEach((l,idx) => {
                    let link = document.createElement('a');
                    let link_txt = document.createTextNode(tags[idx]);
                    link.appendChild(link_txt);
                    link.title = tags[idx];
                    link.href = l;
                    span.appendChild(link);
                    span.appendChild(document.createTextNode(', '));
                })
                span.lastChild.remove();

            }

            // fixes the display of the tags
            document.querySelectorAll('dd.value').forEach(e => {
                let txt = e.textContent;
                let feature = e.previousElementSibling.textContent.trim();
                let tags = []
                let tag_links = []
                if (feature === 'Subject') {
                    txt.split(';').forEach(t => {
                    tags.push(t.trim())
                    tag_links.push(`http://localhost:88/s/test/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=3&property%5B0%5D%5Btype%5D=in&property%5B0%5D%5Btext%5D=${t.trim()}&submit=Search`)
                })    
                create_links(e, tags, tag_links);
                } else if (feature === 'Tag') {
                    txt.split(';').forEach(t => {
                    tags.push(t.trim())
                    tag_links.push(`http://localhost:88/s/test/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=194&property%5B0%5D%5Btype%5D=in&property%5B0%5D%5Btext%5D=${t.trim()}&submit=Search`)
                })
                create_links(e, tags, tag_links);
                }

                

            })

        </script>



        <!--    FIN DE MAPA   -->

        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
            <h4 class="label-tokens">
                <?php echo "Sets"; ?>
            </h4>
            <?php foreach ($itemSets as $itemSet): ?>
                <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>">
                        <?php echo $itemSet->displayTitle(); ?>
                    </a></div>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>

<script>
new SimpleLightbox('.media-render a', { 
    overlayOpacity: 0.9,
    widthRatio: 1.5,
    heightRatio: 1,
    scaleImageToRatio: true,
    //Documentation: https://simplelightbox.com/
 });
</script>