<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/explore.css'));
$this->headScript()->prependFile($this->assetUrl('js/explore.js'));
?>

<body id="body-explorar">
  <ul class="explorar">
    <li>
      <div class="explorsec ancienRegime">  
        <div class='explorsecBox'>
          <h2><a href="#">Ancien Regime</a>
            </h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
      </div>
    </li>
    <li>
      <div class="explorsec empire">
        <div class='explorsecBox'>
          <h2><a href="#">Empire</a>
          </h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
      </div>
    </li>
    <li>
      <div class="explorsec julyMonarchy">
        <div class='explorsecBox'>
          <h2><a href="#">July Monarchy</a>
          </h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
      </div>
    </li>
    <li>
      <div class="explorsec restoration">
        <div class='explorsecBox'>
          <h2><a href="#">Bourbon Restoration</a>
          </h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
      </div>
    </li>
    <li>
      <div class="explorsec revDirectoryConsulate">
        <div class='explorsecBox'>
          <h2><a href="#">Revolution Directory Consulate</a>
          </h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
      </div>
    </li>
  </ul>
</body>