<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/explore.css'));
$this->headScript()->prependFile($this->assetUrl('js/explore.js'));
?>

<body id="body-explorar">
  <ul class="explorar">
    <li>
      <div class="explorsec rutas">
        <h2><a href="#">Ancien Regime</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec autorias">
        <h2><a href="#">Empire</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec series">
        <h2><a href="#">July Monarchy</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec colecciones">
        <h2><a href="#">Restoration</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec etiquetas">
        <h2><a href="#">Revolution Directory Consulate</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec etiquetas">
        <h2><a href="#">Post-1848</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
  </ul>
</body>