<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/explorar.css'));
$this->headScript()->prependFile($this->assetUrl('js/explorar.js'));
?>

<body id="body-explorar">
  <ul class="explorar">
    <li>
      <div class="explorsec rutas">
        <h2><a href="/s/catalogo/item-set?resource_template_id[0]=8&sort_by=title&sort_order=asc">Ancien Regime</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec autorias">
        <h2><a href="/s/catalogo/item-set?resource_template_id%5B0%5D=4&amp;sort_by=title&amp;sort_order=asc&page=1">Empire</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec series">
        <h2><a href="/s/catalogo/item-set?resource_template_id%5B0%5D=5&amp;sort_by=title&amp;sort_order=asc&page=1">July Monarchy</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec colecciones">
        <h2><a href="/s/catalogo/item-set?resource_template_id[0]=6&sort_by=title&sort_order=asc&page=1">Restoration</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec etiquetas">
        <h2><a href="/s/catalogo/reference">Revolution Directory Consulate</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
    <li>
      <div class="explorsec etiquetas">
        <h2><a href="/s/catalogo/reference">Post-1848</a>
        </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
    </li>
  </ul>
</body>