<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<div class="portada-omeka-fondo">
    <div class="portada-omeka-caja">
        <div class="fila">
            <div class="columna portada-omeka-titulo">
                <?php echo $title; ?>
            </div>
            <div class="columna portada-omeka-texto">
                <?php echo $text; ?>
            </div>
        </div>
    </div>
</div>